version: '3'
services:

  influxdb:
    image: "influxdb:1.5"
    ports: ["8086:8086"]

  grafana:
    image: "grafana/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    ports: ["3000:3000"]
    volumes:
    - "./gf-prov-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro"
